/**
 * Post-process a generated .pptx so it carries the two things PowerChart
 * cannot ship without and pptxgenjs cannot write.
 *
 * pptxgenjs has no API for either — grepping the library turns up exactly two
 * `grpSp` hits, both the mandatory zero-size `<p:grpSpPr>` boilerplate every
 * slide has, and zero hits for `custDataLst` or `tagLst`. So a deck it
 * produces is a pile of loose shapes with no identity:
 *
 *   - **Grouping.** A chart has to be one object on the slide — draggable as a
 *     unit, deletable as a unit. Every shape loose is what the live add-in ends
 *     up with when the host refuses `addGroup`, and it is exactly the outcome
 *     this whole path exists to avoid.
 *   - **Tags.** `POWERCHART_CONFIG` on the group is what makes a chart
 *     re-editable; `POWERCHART_DEMO_SLOT` on the slide is what lets the repair
 *     pass pair a slide back to the item it was drawn for.
 *
 * The transform mirrors what real PowerPoint writes, read out of a deck the
 * live add-in produced (`Presentation_4.pptx`): children keep their absolute
 * coordinates untouched, and the group's `chOff`/`chExt` are set EQUAL to its
 * `off`/`ext`, which makes the group transform an identity. Any other choice
 * scales or shifts the chart.
 *
 * String surgery rather than a DOM: the input is machine-generated by a pinned
 * pptxgenjs, so its shape is predictable, and this way the module runs
 * identically in the pane and in a plain Node test. Every step asserts the
 * marker it expects — a pptxgenjs upgrade that changes the output fails loudly
 * here instead of silently producing a deck PowerPoint will not open.
 */

const TAGS_REL_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/tags";
const TAGS_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.presentationml.tags+xml";

const TAG_LST_NS =
  'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' +
  'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" ' +
  'xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"';

/**
 * PowerPoint's canonical 16:9 slide width in EMU. pptxgenjs writes 12191695
 * for the same nominal 13.333in — 305 EMU short, because 13.333 is a rounded
 * decimal and 12192000 is the exact value (13⅓ × 914400). Imperceptible on
 * screen, but a deck whose slide size does not match the destination's is a
 * deck the host may rescale on insert, and rescaling moves every chart.
 */
const CANONICAL_SLIDE_EMU = { cx: 12192000, cy: 6858000 };

/** The name the live renderer gives a chart's group — kept identical here so
 *  `snapshotAddedSlides` recognises a generated chart as a grouped one. */
const GROUP_NAME = "PowerChart";

/** What to add to one slide of the generated deck. */
export interface SlideDressing {
  /** Serialized ChartConfig for the group's `POWERCHART_CONFIG` tag. */
  configJson?: string;
  /** `POWERCHART_ORIGIN` payload: [frameLeft, frameTop, groupLeft, groupTop]. */
  origin?: [number, number, number, number];
  /** Item index for the slide-level `POWERCHART_DEMO_SLOT` tag. */
  slot?: number;
  /** Item title, carried alongside the slot index. */
  title?: string;
  /** Group the slide's shapes. Default true; false leaves them loose. */
  group?: boolean;
}

/** Escape a string for use inside an XML attribute value. */
export function xmlAttr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** A `ppt/tags/tagN.xml` part holding one or more name/value pairs. */
export function tagPart(entries: [string, string][]): string {
  const tags = entries.map(([name, val]) => `<p:tag name="${xmlAttr(name)}" val="${xmlAttr(val)}"/>`).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<p:tagLst ${TAG_LST_NS}>${tags}</p:tagLst>`;
}

/**
 * Split a run of sibling XML elements into top-level elements.
 *
 * Depth-counted rather than regex-matched: a chart slide's shapes nest several
 * levels deep and contain the same tag names at different depths, so anything
 * that pairs `<p:sp>` with the next `</p:sp>` textually gets the wrong one as
 * soon as a shape contains another.
 */
export function topLevelElements(xml: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let start = -1;
  const tag = /<(\/?)([A-Za-z0-9:_-]+)([^>]*?)(\/?)>/g;
  let m: RegExpExecArray | null;
  while ((m = tag.exec(xml))) {
    const closing = m[1] === "/";
    const selfClosing = m[4] === "/";
    if (selfClosing) {
      if (depth === 0) out.push(m[0]);
      continue;
    }
    if (closing) {
      depth--;
      if (depth === 0 && start >= 0) {
        out.push(xml.slice(start, m.index + m[0].length));
        start = -1;
      }
      continue;
    }
    if (depth === 0) start = m.index;
    depth++;
  }
  return out;
}

/** The first `<a:off>`/`<a:ext>` pair in an element — a shape's own frame. */
function frameOf(element: string): { x: number; y: number; cx: number; cy: number } | null {
  const off = /<a:off x="(-?\d+)" y="(-?\d+)"\s*\/>/.exec(element);
  const ext = /<a:ext cx="(\d+)" cy="(\d+)"\s*\/>/.exec(element);
  if (!off || !ext) return null;
  return { x: Number(off[1]), y: Number(off[2]), cx: Number(ext[1]), cy: Number(ext[2]) };
}

/** Highest `<p:cNvPr id>` on the slide — ids must be unique within a slide. */
function maxShapeId(slideXml: string): number {
  let max = 0;
  const ids = /<p:cNvPr[^>]*\bid="(\d+)"/g;
  let m: RegExpExecArray | null;
  while ((m = ids.exec(slideXml))) max = Math.max(max, Number(m[1]));
  return max;
}

/** Next free `rIdN` in a .rels part — relationship ids are scoped per file. */
function nextRelId(relsXml: string): number {
  let max = 0;
  const ids = /Id="rId(\d+)"/g;
  let m: RegExpExecArray | null;
  while ((m = ids.exec(relsXml))) max = Math.max(max, Number(m[1]));
  return max + 1;
}

/**
 * Wrap a slide's shapes in one group.
 *
 * The group's frame is the bounding box of its children, and `chOff`/`chExt`
 * repeat it exactly so the child coordinate space is the slide's own — which
 * is why not a single child element is rewritten. This is what PowerPoint
 * itself writes when a user groups shapes; anything else silently rescales.
 *
 * Returns the XML unchanged when there is nothing to group (fewer than two
 * shapes, or no measurable frame among them).
 */
export function groupSlideShapes(slideXml: string, groupTagRid?: string): string {
  const treeOpen = slideXml.indexOf("<p:spTree>");
  const treeClose = slideXml.indexOf("</p:spTree>");
  if (treeOpen < 0 || treeClose < 0) throw new Error("ooxml: slide has no <p:spTree>");
  const headerEnd = slideXml.indexOf("</p:grpSpPr>", treeOpen);
  if (headerEnd < 0 || headerEnd > treeClose) throw new Error("ooxml: slide tree has no root <p:grpSpPr>");
  const bodyStart = headerEnd + "</p:grpSpPr>".length;
  const body = slideXml.slice(bodyStart, treeClose);
  const children = topLevelElements(body);
  if (children.length < 2) return slideXml;

  const frames = children.map(frameOf).filter((f): f is NonNullable<typeof f> => !!f);
  if (!frames.length) return slideXml;
  const x = Math.min(...frames.map((f) => f.x));
  const y = Math.min(...frames.map((f) => f.y));
  const cx = Math.max(...frames.map((f) => f.x + f.cx)) - x;
  const cy = Math.max(...frames.map((f) => f.y + f.cy)) - y;

  const id = maxShapeId(slideXml) + 1;
  const nvPr = groupTagRid
    ? `<p:nvPr><p:custDataLst><p:tags r:id="${groupTagRid}"/></p:custDataLst></p:nvPr>`
    : "<p:nvPr/>";
  const group =
    `<p:grpSp><p:nvGrpSpPr><p:cNvPr id="${id}" name="${GROUP_NAME}"/><p:cNvGrpSpPr/>${nvPr}</p:nvGrpSpPr>` +
    `<p:grpSpPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${cx}" cy="${cy}"/>` +
    `<a:chOff x="${x}" y="${y}"/><a:chExt cx="${cx}" cy="${cy}"/></a:xfrm></p:grpSpPr>` +
    `${body}</p:grpSp>`;
  return slideXml.slice(0, bodyStart) + group + slideXml.slice(treeClose);
}

/**
 * Attach a slide-level `<p:custDataLst>`, which is where a slide's own tags
 * live: a direct child of `<p:cSld>`, after `</p:spTree>` and before
 * `<p:extLst>` — the order `CT_CommonSlideData` requires.
 */
export function tagSlide(slideXml: string, rid: string): string {
  const treeClose = slideXml.indexOf("</p:spTree>");
  if (treeClose < 0) throw new Error("ooxml: slide has no <p:spTree>");
  const at = treeClose + "</p:spTree>".length;
  return `${slideXml.slice(0, at)}<p:custDataLst><p:tags r:id="${rid}"/></p:custDataLst>${slideXml.slice(at)}`;
}

/** Append a relationship to a .rels part. */
function addRelationship(relsXml: string, id: string, type: string, target: string): string {
  const close = relsXml.lastIndexOf("</Relationships>");
  if (close < 0) throw new Error("ooxml: malformed .rels part");
  return `${relsXml.slice(0, close)}<Relationship Id="${id}" Type="${type}" Target="${target}"/>${relsXml.slice(close)}`;
}

/** Declare a part's content type — a tags part is invalid without this. */
function addContentTypeOverride(typesXml: string, partName: string, contentType: string): string {
  const close = typesXml.lastIndexOf("</Types>");
  if (close < 0) throw new Error("ooxml: malformed [Content_Types].xml");
  return `${typesXml.slice(0, close)}<Override PartName="${partName}" ContentType="${contentType}"/>${typesXml.slice(close)}`;
}

/**
 * Force the deck to PowerPoint's exact 16:9 size. See CANONICAL_SLIDE_EMU —
 * pptxgenjs is 305 EMU narrow, and a size mismatch invites the host to rescale
 * the slides it inserts.
 */
export function canonicalSlideSize(presentationXml: string): string {
  return presentationXml.replace(
    /<p:sldSz[^>]*\/>/,
    `<p:sldSz cx="${CANONICAL_SLIDE_EMU.cx}" cy="${CANONICAL_SLIDE_EMU.cy}"/>`,
  );
}

/**
 * Apply grouping and tags to a base64 .pptx, returning a new base64 .pptx.
 *
 * `dressing[i]` describes `ppt/slides/slide{i+1}.xml` — pptxgenjs numbers
 * slides in the order they were added, which is the order the caller built
 * them in.
 */
export async function injectGroupsAndTags(
  base64: string,
  dressing: SlideDressing[],
): Promise<{ base64: string; shapesPerSlide: number[] }> {
  const { default: JSZip } = await import("jszip");
  const zip = await JSZip.loadAsync(base64, { base64: true });

  let types = await readPart(zip, "[Content_Types].xml");
  let tagPartNo = 0;
  // What each slide ACTUALLY holds. The caller cannot infer it: this renderer
  // draws a pie as one custGeom wedge where the Office.js one draws a
  // sixteen-triangle fan, so `estimateOfficeShapes` is the wrong yardstick
  // here — measuring a perfect pie at 10 of 50 shapes and calling it wreckage.
  const shapesPerSlide: number[] = [];

  for (let i = 0; i < dressing.length; i++) {
    const item = dressing[i];
    const slidePath = `ppt/slides/slide${i + 1}.xml`;
    const relsPath = `ppt/slides/_rels/slide${i + 1}.xml.rels`;
    let slide = await readPart(zip, slidePath);
    let rels = await readPart(zip, relsPath);

    // The group's own tag part carries config + origin together: one shape may
    // reference only ONE tags part, and a part may hold many tags.
    let groupRid: string | undefined;
    const groupTags: [string, string][] = [];
    if (item.configJson) groupTags.push(["POWERCHART_CONFIG", item.configJson]);
    if (item.origin) groupTags.push(["POWERCHART_ORIGIN", JSON.stringify(item.origin)]);
    if (groupTags.length) {
      const n = ++tagPartNo;
      groupRid = `rId${nextRelId(rels)}`;
      zip.file(`ppt/tags/tag${n}.xml`, tagPart(groupTags));
      rels = addRelationship(rels, groupRid, TAGS_REL_TYPE, `../tags/tag${n}.xml`);
      types = addContentTypeOverride(types, `/ppt/tags/tag${n}.xml`, TAGS_CONTENT_TYPE);
    }

    shapesPerSlide.push(countSlideShapes(slide));
    if (item.group !== false) slide = groupSlideShapes(slide, groupRid);

    if (item.slot !== undefined) {
      const n = ++tagPartNo;
      const slotRid = `rId${nextRelId(rels)}`;
      zip.file(
        `ppt/tags/tag${n}.xml`,
        tagPart([["POWERCHART_DEMO_SLOT", JSON.stringify({ i: item.slot, title: item.title ?? null })]]),
      );
      rels = addRelationship(rels, slotRid, TAGS_REL_TYPE, `../tags/tag${n}.xml`);
      types = addContentTypeOverride(types, `/ppt/tags/tag${n}.xml`, TAGS_CONTENT_TYPE);
      slide = tagSlide(slide, slotRid);
    }

    zip.file(slidePath, slide);
    zip.file(relsPath, rels);
  }

  zip.file("[Content_Types].xml", types);
  zip.file("ppt/presentation.xml", canonicalSlideSize(await readPart(zip, "ppt/presentation.xml")));
  return { base64: await zip.generateAsync({ type: "base64" }), shapesPerSlide };
}

/** Top-level shapes on a slide, before it is grouped. */
export function countSlideShapes(slideXml: string): number {
  const treeClose = slideXml.indexOf("</p:spTree>");
  const headerEnd = slideXml.indexOf("</p:grpSpPr>");
  if (treeClose < 0 || headerEnd < 0 || headerEnd > treeClose) return 0;
  return topLevelElements(slideXml.slice(headerEnd + "</p:grpSpPr>".length, treeClose)).length;
}

/** Read a part, failing loudly when the generator's layout has moved. */
async function readPart(zip: { file(path: string): { async(t: "string"): Promise<string> } | null }, path: string) {
  const entry = zip.file(path);
  if (!entry) throw new Error(`ooxml: generated deck has no ${path}`);
  return entry.async("string");
}
