/**
 * Post-process a generated .pptx so it carries the two things SSF Charts
 * cannot ship without and pptxgenjs cannot write.
 *
 * pptxgenjs has no API for either — grepping the library turns up exactly two
 * `grpSp` hits, both the mandatory zero-size `<p:grpSpPr>` boilerplate every
 * slide has, and zero hits for `custDataLst` or `tagLst`. So a deck it
 * produces is a pile of loose shapes with no identity:
 *
 *   - **Grouping.** A chart has to be one object on the slide — draggable as a
 *     unit, deletable as a unit. Every shape loose is what the live add-in ends
 *     up with when the host refuses `addGroup`, and it is exactly the outcome
 *     this whole path exists to avoid.
 *   - **Tags.** `POWERCHART_CONFIG` on the group is what makes a chart
 *     re-editable; `POWERCHART_DEMO_SLOT` on the slide is what lets the repair
 *     pass pair a slide back to the item it was drawn for.
 *
 * The transform mirrors what real PowerPoint writes, read out of a deck the
 * live add-in produced (`Presentation_4.pptx`): children keep their absolute
 * coordinates untouched, and the group's `chOff`/`chExt` are set EQUAL to its
 * `off`/`ext`, which makes the group transform an identity. Any other choice
 * scales or shifts the chart.
 *
 * String surgery rather than a DOM: the input is machine-generated by a pinned
 * pptxgenjs, so its shape is predictable, and this way the module runs
 * identically in the pane and in a plain Node test. Every step asserts the
 * marker it expects — a pptxgenjs upgrade that changes the output fails loudly
 * here instead of silently producing a deck PowerPoint will not open.
 */
import { xmlText } from "./svg";

const TAGS_REL_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/tags";
const TAGS_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.presentationml.tags+xml";

const TAG_LST_NS =
  'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ' +
  'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" ' +
  'xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"';

/**
 * PowerPoint's canonical 16:9 slide width in EMU. pptxgenjs writes 12191695
 * for the same nominal 13.333in — 305 EMU short, because 13.333 is a rounded
 * decimal and 12192000 is the exact value (13⅓ × 914400). Imperceptible on
 * screen, but a deck whose slide size does not match the destination's is a
 * deck the host may rescale on insert, and rescaling moves every chart.
 */
const CANONICAL_SLIDE_EMU = { cx: 12192000, cy: 6858000 };

/** EMU per point. 914400 EMU to the inch, 72 points to the inch. */
export const EMU_PER_POINT = 12700;

/**
 * The slide size a .pptx declares, in EMU, or null if it does not say.
 *
 * `ppt/presentation.xml` carries exactly one `<p:sldSz cx=".." cy=".."/>`, and
 * it is the authoritative statement of a deck's dimensions — the thing every
 * "what size is this slide?" question actually wants. Reading it out of a deck
 * the HOST exported is how this add-in learns the size of the presentation it
 * is running in on hosts too old for `PageSetup`; see `slideSize`.
 *
 * Attribute order is not guaranteed, so both are matched independently rather
 * than with one positional pattern.
 */
export function parseSlideSizeEmu(presentationXml: string): { cx: number; cy: number } | null {
  const tag = /<p:sldSz\b[^>]*\/?>/.exec(presentationXml);
  if (!tag) return null;
  const cx = /\bcx="(\d+)"/.exec(tag[0]);
  const cy = /\bcy="(\d+)"/.exec(tag[0]);
  if (!cx || !cy) return null;
  const w = Number(cx[1]);
  const h = Number(cy[1]);
  // A zero or non-finite dimension is not a slide. Returning it would put a
  // divide-by-zero into every aspect-ratio calculation downstream.
  if (!Number.isFinite(w) || !Number.isFinite(h) || w <= 0 || h <= 0) return null;
  return { cx: w, cy: h };
}

/** The name the live renderer gives a chart's group — kept identical here so
 *  `snapshotAddedSlides` recognises a generated chart as a grouped one.
 *
 *  NOT renamed with the product on 2026-08-27: it is written into the deck and
 *  matched on read. See `CHART_TAG` in `powerpoint.ts`. */
const GROUP_NAME = "PowerChart";

/** What to add to one slide of the generated deck. */
export interface SlideDressing {
  /** Serialized ChartConfig for the group's `POWERCHART_CONFIG` tag. */
  configJson?: string;
  /** `POWERCHART_ORIGIN` payload: [frameLeft, frameTop, groupLeft, groupTop]. */
  origin?: [number, number, number, number];
  /**
   * `POWERCHART_SCENE`: the fingerprint of the scene these shapes were drawn
   * from, so the chart's first in-place update has something to diff against.
   *
   * WITHOUT IT EVERY DECK CHART IS PERMANENTLY REDRAW-ONLY. `tryInPlaceUpdate`
   * refuses a chart with no fingerprint — "it was drawn by an older build" —
   * and that message was wrong about these: they were drawn by THIS builder,
   * which had never written one. Rounds 143 and 144 both show charts 1/8, 2/8
   * and 3/8 updating past the check while 4/8 through 8/8 refuse, and the split
   * is exactly which charts came from `insertSceneIntoSlide` and which arrived
   * in the generated deck.
   */
  sceneTag?: string;
  /** Item index for the slide-level `POWERCHART_DEMO_SLOT` tag. */
  slot?: number;
  /** Item title, carried alongside the slot index. */
  title?: string;
  /**
   * Token identifying the run that produced this deck, carried in the slot tag
   * so a repair pass can tell these slides from an earlier run's. Omitted
   * unless the caller supplies one — the skill's own output must stay
   * byte-deterministic, and a per-build token would not be.
   */
  run?: string;
  /** Group the slide's shapes. Default true; false leaves them loose. */
  group?: boolean;
  /**
   * The chart's text alternative, written as the group's OOXML `descr` — what
   * PowerPoint shows under "Edit Alt Text" and what a screen reader announces.
   *
   * `skill/reference.md` recorded this as a limit of the headless renderer on
   * the grounds that pptxgenjs exposes alt text on pictures and native charts
   * only. That is true OF PPTXGENJS and stopped one step short: this module
   * already hand-patches the slide XML, and it writes the very element alt text
   * lives on — the group's `<p:cNvPr>`. The SVG renderer emits `<title>`/`<desc>`
   * and the Office.js renderer sets `altTextDescription`, so the generated deck
   * was the one output of the three with no text alternative at all.
   */
  desc?: string;
}

/**
 * Escape a string for use inside an XML attribute value.
 *
 * `xmlText` FIRST, like the two sibling sinks (`svg.ts`, `pptx-paint.mjs`) and
 * for the reason their comment gives: XML 1.0 forbids those characters
 * outright, so they cannot be escaped, only removed. This third sink never got
 * it, and it is the one that writes `ppt/tags/tagN.xml` — where the entire
 * serialized ChartConfig lands as an attribute value. `JSON.stringify` escapes
 * C0 controls and lone surrogates but NOT U+FFFE/U+FFFF, so those reached the
 * tag part raw: the slide XML came out clean, the tags part was not
 * well-formed, and PowerPoint offered to repair a file both the skill CLI and
 * the add-in had reported as a success.
 */
export function xmlAttr(value: string): string {
  return xmlText(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** A `ppt/tags/tagN.xml` part holding one or more name/value pairs. */
export function tagPart(entries: [string, string][]): string {
  const tags = entries.map(([name, val]) => `<p:tag name="${xmlAttr(name)}" val="${xmlAttr(val)}"/>`).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<p:tagLst ${TAG_LST_NS}>${tags}</p:tagLst>`;
}

/**
 * Split a run of sibling XML elements into top-level elements.
 *
 * Depth-counted rather than regex-matched: a chart slide's shapes nest several
 * levels deep and contain the same tag names at different depths, so anything
 * that pairs `<p:sp>` with the next `</p:sp>` textually gets the wrong one as
 * soon as a shape contains another.
 */
export function topLevelElements(xml: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let start = -1;
  // The attribute part is matched as "quoted strings or non-'>' characters",
  // not simply "anything up to the first >". A raw `>` inside an attribute
  // VALUE is not the end of the tag, and reading it as one ends the element
  // early and desyncs `depth` for the entire rest of the slide — after which
  // this returns nothing at all and the chart is never grouped. Well-formed
  // XML never contains one, but this parses bytes some other library wrote:
  // pptxgenjs emits `typeface="…"` without escaping it (see `xmlFontName` in
  // pptx-paint.mjs), and being one unescaped attribute away from silently
  // losing every shape on a slide is not a place to stand.
  const tag = /<(\/?)([A-Za-z0-9:_-]+)((?:"[^"]*"|'[^']*'|[^>"'])*?)(\/?)>/g;
  let m: RegExpExecArray | null;
  while ((m = tag.exec(xml))) {
    const closing = m[1] === "/";
    const selfClosing = m[4] === "/";
    if (selfClosing) {
      if (depth === 0) out.push(m[0]);
      continue;
    }
    if (closing) {
      depth--;
      if (depth === 0 && start >= 0) {
        out.push(xml.slice(start, m.index + m[0].length));
        start = -1;
      }
      continue;
    }
    if (depth === 0) start = m.index;
    depth++;
  }
  return out;
}

/** The first `<a:off>`/`<a:ext>` pair in an element — a shape's own frame. */
function frameOf(element: string): { x: number; y: number; cx: number; cy: number } | null {
  const off = /<a:off x="(-?\d+)" y="(-?\d+)"\s*\/>/.exec(element);
  const ext = /<a:ext cx="(\d+)" cy="(\d+)"\s*\/>/.exec(element);
  if (!off || !ext) return null;
  return { x: Number(off[1]), y: Number(off[2]), cx: Number(ext[1]), cy: Number(ext[2]) };
}

/** Highest `<p:cNvPr id>` on the slide — ids must be unique within a slide. */
function maxShapeId(slideXml: string): number {
  let max = 0;
  const ids = /<p:cNvPr[^>]*\bid="(\d+)"/g;
  let m: RegExpExecArray | null;
  while ((m = ids.exec(slideXml))) max = Math.max(max, Number(m[1]));
  return max;
}

/** Next free `rIdN` in a .rels part — relationship ids are scoped per file. */
function nextRelId(relsXml: string): number {
  let max = 0;
  const ids = /Id="rId(\d+)"/g;
  let m: RegExpExecArray | null;
  while ((m = ids.exec(relsXml))) max = Math.max(max, Number(m[1]));
  return max + 1;
}

/**
 * Wrap a slide's shapes in one group.
 *
 * The group's frame is the bounding box of its children, and `chOff`/`chExt`
 * repeat it exactly so the child coordinate space is the slide's own — which
 * is why not a single child element is rewritten. This is what PowerPoint
 * itself writes when a user groups shapes; anything else silently rescales.
 *
 * Returns the XML unchanged when there is nothing to group (fewer than two
 * shapes, or no measurable frame among them).
 */
export function groupSlideShapes(slideXml: string, groupTagRid?: string, descr?: string): string {
  const treeOpen = slideXml.indexOf("<p:spTree>");
  const treeClose = slideXml.indexOf("</p:spTree>");
  if (treeOpen < 0 || treeClose < 0) throw new Error("ooxml: slide has no <p:spTree>");
  const headerEnd = slideXml.indexOf("</p:grpSpPr>", treeOpen);
  if (headerEnd < 0 || headerEnd > treeClose) throw new Error("ooxml: slide tree has no root <p:grpSpPr>");
  const bodyStart = headerEnd + "</p:grpSpPr>".length;
  const body = slideXml.slice(bodyStart, treeClose);
  const children = topLevelElements(body);
  if (children.length < 2) return slideXml;

  const frames = children.map(frameOf).filter((f): f is NonNullable<typeof f> => !!f);
  if (!frames.length) return slideXml;
  // Reduced, not spread, for the reason the datasheet's formula engine already
  // carries twice: `Math.min(...arr)` passes one ARGUMENT per element, so the
  // bound comes from the data and a big enough slide overflows the stack rather
  // than returning a wrong answer. The trigger here is synthetic — it takes
  // ~150k top-level shapes on one slide, and this module is handed decks by a
  // library caller — but the loop costs the same and has no bound at all.
  const least = (pick: (f: (typeof frames)[number]) => number) =>
    frames.reduce((a, f) => Math.min(a, pick(f)), Infinity);
  const most = (pick: (f: (typeof frames)[number]) => number) =>
    frames.reduce((a, f) => Math.max(a, pick(f)), -Infinity);
  const x = least((f) => f.x);
  const y = least((f) => f.y);
  const cx = most((f) => f.x + f.cx) - x;
  const cy = most((f) => f.y + f.cy) - y;

  const id = maxShapeId(slideXml) + 1;
  // `descr` is PowerPoint's alt text. Escaped through `xmlAttr` like every other
  // attribute this module writes, and omitted entirely when there is nothing to
  // say — an empty `descr=""` is not "no alt text", it is alt text that says
  // nothing, which reads to a screen-reader user as a described object with an
  // empty description.
  const alt = descr ? ` descr="${xmlAttr(descr)}"` : "";
  const nvPr = groupTagRid
    ? `<p:nvPr><p:custDataLst><p:tags r:id="${groupTagRid}"/></p:custDataLst></p:nvPr>`
    : "<p:nvPr/>";
  const group =
    `<p:grpSp><p:nvGrpSpPr><p:cNvPr id="${id}" name="${GROUP_NAME}"${alt}/><p:cNvGrpSpPr/>${nvPr}</p:nvGrpSpPr>` +
    `<p:grpSpPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${cx}" cy="${cy}"/>` +
    `<a:chOff x="${x}" y="${y}"/><a:chExt cx="${cx}" cy="${cy}"/></a:xfrm></p:grpSpPr>` +
    `${body}</p:grpSp>`;
  return slideXml.slice(0, bodyStart) + group + slideXml.slice(treeClose);
}

/**
 * Put a tag reference on the slide's first shape.
 *
 * The fallback for a slide `groupSlideShapes` declined to group — an
 * image-mode chart is one picture, and one shape is not a group. Without this
 * such a chart carries no `POWERCHART_CONFIG` at all and the pane cannot
 * re-open it, which is the difference between a picture of a chart and a
 * chart. `<p:nvPr>` is where `custDataLst` belongs on both `<p:sp>` and
 * `<p:pic>`, so the same insertion works for either.
 */
export function tagFirstShape(slideXml: string, rid: string): string {
  const at = slideXml.indexOf("</p:grpSpPr>");
  if (at < 0) return slideXml;
  // And NAME it, because a tag nobody can find is not a chart.
  //
  // Every downstream consumer keys on the single string "PowerChart":
  // `retagSlideChart`, `rescueGroupAndTag`, `slideHoldsOnlyChart` and
  // `snapshotAddedSlides` in `powerpoint.ts`, and `verify-deck`'s own
  // chart-object test. This fallback hung the config on whatever pptxgenjs had
  // called the shape — `Text 0` — so an ordinary "no data yet" chart (a pie,
  // treemap, funnel or violin with empty categories or all-zero values, which
  // makes `groupSlideShapes` decline at fewer than two children) shipped
  // re-editable in the file and invisible to every path that looks for one.
  //
  // AFTER `at`, always. The first `<p:cNvPr>` in a slide belongs to the shape
  // TREE itself — `<p:cNvPr id="1" name=""/>` inside `<p:nvGrpSpPr>` — so a
  // whole-document replace renamed the tree and left the shape as "Text 0",
  // which reads exactly like a fix and is none.
  const NAMED = new RegExp('(<p:cNvPr[^>]*?name=")[^"]*(")');
  const head = slideXml.slice(0, at);
  const tail = slideXml.slice(at).replace(NAMED, (_m, open, close) => open + GROUP_NAME + close);
  slideXml = head + tail;
  const empty = slideXml.indexOf("<p:nvPr/>", at);
  if (empty >= 0) {
    return (
      slideXml.slice(0, empty) +
      `<p:nvPr><p:custDataLst><p:tags r:id="${rid}"/></p:custDataLst></p:nvPr>` +
      slideXml.slice(empty + "<p:nvPr/>".length)
    );
  }
  const open = slideXml.indexOf("<p:nvPr>", at);
  if (open < 0) return slideXml;
  const close = slideXml.indexOf("</p:nvPr>", open);
  if (close < 0) return slideXml;
  // `CT_ApplicationNonVisualDrawingProps` orders its children `ph?, media?,
  // custDataLst?, extLst?`, so on a placeholder shape the tag has to go AFTER
  // the `<p:ph>`. Prepending it produces a part PowerPoint will not open.
  const inner = slideXml.slice(open + "<p:nvPr>".length, close);
  const ph = /<p:ph\b[^>]*(?:\/>|>[\s\S]*?<\/p:ph>)/.exec(inner);
  const at2 = open + "<p:nvPr>".length + (ph ? ph.index + ph[0].length : 0);
  return slideXml.slice(0, at2) + `<p:custDataLst><p:tags r:id="${rid}"/></p:custDataLst>` + slideXml.slice(at2);
}

/**
 * Attach a slide-level `<p:custDataLst>`, which is where a slide's own tags
 * live: a direct child of `<p:cSld>`, after `</p:spTree>` and before
 * `<p:extLst>` — the order `CT_CommonSlideData` requires.
 */
export function tagSlide(slideXml: string, rid: string): string {
  const treeClose = slideXml.indexOf("</p:spTree>");
  if (treeClose < 0) throw new Error("ooxml: slide has no <p:spTree>");
  const at = treeClose + "</p:spTree>".length;
  return `${slideXml.slice(0, at)}<p:custDataLst><p:tags r:id="${rid}"/></p:custDataLst>${slideXml.slice(at)}`;
}

/** Append a relationship to a .rels part. */
function addRelationship(relsXml: string, id: string, type: string, target: string): string {
  const close = relsXml.lastIndexOf("</Relationships>");
  if (close < 0) throw new Error("ooxml: malformed .rels part");
  return `${relsXml.slice(0, close)}<Relationship Id="${id}" Type="${type}" Target="${target}"/>${relsXml.slice(close)}`;
}

/** Declare a part's content type — a tags part is invalid without this. */
function addContentTypeOverride(typesXml: string, partName: string, contentType: string): string {
  const close = typesXml.lastIndexOf("</Types>");
  if (close < 0) throw new Error("ooxml: malformed [Content_Types].xml");
  return `${typesXml.slice(0, close)}<Override PartName="${partName}" ContentType="${contentType}"/>${typesXml.slice(close)}`;
}

/**
 * Pin the deck's declared slide size.
 *
 * Defaults to PowerPoint's exact 16:9 (see CANONICAL_SLIDE_EMU — pptxgenjs is
 * 305 EMU narrow), because that is what this generator lays out for and what
 * most decks are. But "most" is not "all", and the default was applied
 * unconditionally: a generated deck inserted into a 4:3 presentation declared
 * 16:9, which is precisely the size mismatch this function's own comment warns
 * invites the host to rescale on insert. Every chart on the fast path then
 * landed rescaled and off-centre, on a whole class of deck, silently.
 *
 * So the size is now an argument. `slideSize()` reads the destination's real
 * dimensions; passing them makes the generated deck agree with the deck it is
 * going into, which is the condition under which no rescaling happens at all.
 *
 * A size this function will not write falls back to the canonical 16:9, which
 * is what happens when no size is passed at all — the documented default,
 * rather than a throw that would take down an insert over a layout hint. That
 * is the same trade `slideSize()` makes when its own ladder runs out.
 */
export function canonicalSlideSize(
  presentationXml: string,
  emu: { cx: number; cy: number } = CANONICAL_SLIDE_EMU,
): string {
  const size = usableSlideEmu(emu) ?? CANONICAL_SLIDE_EMU;
  return presentationXml.replace(/<p:sldSz[^>]*\/>/, `<p:sldSz cx="${size.cx}" cy="${size.cy}"/>`);
}

/**
 * A slide size this file is willing to WRITE — the same rule `parseSlideSizeEmu`
 * uses to decide what it is willing to READ.
 *
 * The two disagreed, and only one of them was checking. Every value that
 * function rejects went straight into `<p:sldSz>` verbatim: `cx="NaN"`,
 * `cx="0"`, `cx="-12192000"`, `cx="Infinity"`, `cx="wide"`. None is a
 * `ST_PositiveCoordinate`, so PowerPoint offers to repair the deck — and
 * `injectGroupsAndTags` is exported as library API, where this module's own
 * comment already sets the standard: no promise about what it is handed, and
 * silently producing an un-openable file is not a contract worth keeping by
 * luck.
 *
 * Rounded because the type is an INTEGER count of EMU. A caller computing
 * `points * EMU_PER_POINT` gets a fraction for any non-integral point size, and
 * `cx="12192000.7"` fails the schema exactly as the others do — quietly, since
 * it is a perfectly finite positive number and looks right in a diff.
 */
function usableSlideEmu(emu: { cx: number; cy: number }): { cx: number; cy: number } | null {
  const cx = Math.round(emu?.cx as number);
  const cy = Math.round(emu?.cy as number);
  if (!Number.isFinite(cx) || !Number.isFinite(cy) || cx <= 0 || cy <= 0) return null;
  return { cx, cy };
}

/**
 * Apply grouping and tags to a base64 .pptx, returning a new base64 .pptx.
 *
 * `dressing[i]` describes `ppt/slides/slide{i+1}.xml` — pptxgenjs numbers
 * slides in the order they were added, which is the order the caller built
 * them in.
 */
export async function injectGroupsAndTags(
  base64: string,
  dressing: SlideDressing[],
  /** Destination slide size in EMU. Omitted, the deck declares 16:9. */
  slideEmu?: { cx: number; cy: number },
): Promise<{ base64: string; shapesPerSlide: number[] }> {
  const { default: JSZip } = await import("jszip");
  const zip = await JSZip.loadAsync(base64, { base64: true });

  // One dressing entry per slide, or nothing below can be trusted: the two are
  // paired strictly by position, so a caller whose slide count and dressing
  // length drift apart gets every later chart's config on the wrong slide.
  // A dressing LONGER than the deck already failed loudly, on the missing
  // slide part. A shorter one silently left the trailing slides ungrouped and
  // untagged — a pile of loose shapes with no identity, which is the exact
  // outcome this whole module exists to prevent. Fail the same way in both
  // directions.
  const slideCount = Object.keys(zip.files).filter((f) => /^ppt\/slides\/slide\d+\.xml$/.test(f)).length;
  if (slideCount !== dressing.length) {
    throw new Error(`ooxml: generated deck has ${slideCount} slide(s) but ${dressing.length} dressing entr(ies)`);
  }

  let types = await readPart(zip, "[Content_Types].xml");
  // Number new tag parts ABOVE whatever the deck already carries. Starting at
  // 1 unconditionally was safe only because pptxgenjs emits no `ppt/tags/*` of
  // its own — `zip.file()` is a plain overwrite, so the first tag written
  // would silently destroy an existing `tag1.xml` and every slide pointing at
  // it. This function is exported as library API with no promise about what it
  // is handed, and "silently destroys the caller's data" is not a contract
  // worth keeping by luck.
  let tagPartNo = Object.keys(zip.files).reduce((max, f) => {
    const m = /^ppt\/tags\/tag(\d+)\.xml$/.exec(f);
    return m ? Math.max(max, Number(m[1])) : max;
  }, 0);
  // What each slide ACTUALLY holds. The caller cannot infer it: this renderer
  // draws a pie as one custGeom wedge where the Office.js one draws a
  // sixteen-triangle fan, so `estimateOfficeShapes` is the wrong yardstick
  // here — measuring a perfect pie at 10 of 50 shapes and calling it wreckage.
  const shapesPerSlide: number[] = [];

  for (let i = 0; i < dressing.length; i++) {
    const item = dressing[i];
    const slidePath = `ppt/slides/slide${i + 1}.xml`;
    const relsPath = `ppt/slides/_rels/slide${i + 1}.xml.rels`;
    let slide = await readPart(zip, slidePath);
    let rels = await readPart(zip, relsPath);

    // The group's own tag part carries config + origin together: one shape may
    // reference only ONE tags part, and a part may hold many tags.
    let groupRid: string | undefined;
    const groupTags: [string, string][] = [];
    if (item.configJson) groupTags.push(["POWERCHART_CONFIG", item.configJson]);
    if (item.origin) groupTags.push(["POWERCHART_ORIGIN", JSON.stringify(item.origin)]);
    // Beside the config, in the same part: one shape may reference only one tags
    // part, and the update path needs BOTH to take the fast path at all.
    if (item.sceneTag) groupTags.push(["POWERCHART_SCENE", item.sceneTag]);
    if (groupTags.length) {
      const n = ++tagPartNo;
      groupRid = `rId${nextRelId(rels)}`;
      zip.file(`ppt/tags/tag${n}.xml`, tagPart(groupTags));
      rels = addRelationship(rels, groupRid, TAGS_REL_TYPE, `../tags/tag${n}.xml`);
      types = addContentTypeOverride(types, `/ppt/tags/tag${n}.xml`, TAGS_CONTENT_TYPE);
    }

    shapesPerSlide.push(countSlideShapes(slide));
    if (item.group !== false) {
      const grouped = groupSlideShapes(slide, groupRid, item.desc);
      // A one-shape slide has nothing to group — an image-mode chart is a
      // single picture — but it still needs its config tag, or it is not
      // re-editable. Hang it on the shape itself.
      slide = grouped === slide && groupRid ? tagFirstShape(slide, groupRid) : grouped;
    }

    if (item.slot !== undefined) {
      const n = ++tagPartNo;
      const slotRid = `rId${nextRelId(rels)}`;
      zip.file(
        `ppt/tags/tag${n}.xml`,
        tagPart([
          [
            "POWERCHART_DEMO_SLOT",
            JSON.stringify({
              i: item.slot,
              title: item.title ?? null,
              // Only when given — see `SlideDressing.run`. An always-present
              // token would change the showcase deck's bytes on every build.
              ...(item.run === undefined ? {} : { run: item.run }),
            }),
          ],
        ]),
      );
      rels = addRelationship(rels, slotRid, TAGS_REL_TYPE, `../tags/tag${n}.xml`);
      types = addContentTypeOverride(types, `/ppt/tags/tag${n}.xml`, TAGS_CONTENT_TYPE);
      slide = tagSlide(slide, slotRid);
    }

    zip.file(slidePath, slide);
    zip.file(relsPath, rels);
  }

  zip.file("[Content_Types].xml", types);
  zip.file("ppt/presentation.xml", canonicalSlideSize(await readPart(zip, "ppt/presentation.xml"), slideEmu));
  return { base64: await zip.generateAsync({ type: "base64" }), shapesPerSlide };
}

/** Top-level shapes on a slide, before it is grouped. */
export function countSlideShapes(slideXml: string): number {
  const treeClose = slideXml.indexOf("</p:spTree>");
  const headerEnd = slideXml.indexOf("</p:grpSpPr>");
  if (treeClose < 0 || headerEnd < 0 || headerEnd > treeClose) return 0;
  return topLevelElements(slideXml.slice(headerEnd + "</p:grpSpPr>".length, treeClose)).length;
}

/** Read a part, failing loudly when the generator's layout has moved. */
async function readPart(zip: { file(path: string): { async(t: "string"): Promise<string> } | null }, path: string) {
  const entry = zip.file(path);
  if (!entry) throw new Error(`ooxml: generated deck has no ${path}`);
  return entry.async("string");
}
